module.exports = {
                    GeneralError: "Kindly try again later , This is on us",
                    BadRequest : "Bad Request, Some fields are required",
                    CustomerExist : "A Customer with the email/phone exists",
                    InvalidCredentials: "Invalid Credentials.",
                    OtpSentSuccessfully: "An otp has been sent to your email/phone",
                    OtpResentSentSuccessfully: "We just resent your otp to email/phone",
                    OtpMismatch: "Invalid OTP or Customer Supplied",
                    OtpExpired: "OTP Verification has expired, kindly request a new one",
                    OtpVerificationSuccessful: "You have successfully verified your phone number.",
                    EmailVerificationSuccessful: "You have successfully verified your email address.",
                    EmailVerificationHasExpired: "Email Verification Has Expired.",
                    EmailHasNotBeenVerified: "Email Has Not Been Verified.",
                    InvalidToken: "Invalid Token",
                    InvalidSavingsSchedule: "Invalid Saving Schedule.",
                    CustomerCreated: "Account Created",
                    CustomerDetailsFetched: "User details successfully fetched",
                    UnableToLoadCustomerDetails: "Unable To Load Customer Details.",
                    CustomerCreationFailed: "Customer Creation Failed.",
                    BVNExist: "You have a bvn linked to your profile.",
                    BVNValidated: "Bvn validated",
                    BVNDOBMismatch: "Your BVN or date of birth isnt right. Please, check again.",
                    BVNLinkedToAnotherAccount: "Sorry, this bvn has been linked to another wealth buddy account.",
                    BVNLinkedToAccountSuccessfully: "BVN Successfully Linked to Account.",
                    BVNValidationFailed: "Sorry, we couldnt confirm your BVN. Please, try again.",
                    ErrorOccuredWhileVerifyingEmail: "Error Occured While Verifying Email.",
                    InvalidEmail: "This Email is Invalid.",
                    LoginSuccessful: "Login Successful.",
                    PasswordChangedSuccessfully: "Password Changed Successfully.",
                    SQlTransactionNotInitialized: "SQl Transaction is not initialized.",
                    InitializeTransactionError: "Something went wrong while initializng transaction.",
                    SuccessfulTransactionInitialization: "Successfully initialized transaction.",
                    ConsumerError: "Error Occured While Consuming Message.",
                    ProducerError: "Error Occured While Producing Message.",
                    TopicNotHandled: "Topic not handled.",
                    MessageReceivedByConsumer: "Message received by Consumer.",
                    ConsumerRetrialLogError: "Error occurred while attempting to log failed message to temporal database from consumer.",
                    ProducerRetrialLogError: "Error occurred while attempting to log failed message to temporal database from producer.",
                    ResetPasswordSuccessfully: "Kindly check your mail to proceed with your password reset.",
                    ChangeCustomerPasswordSuccessful: "Your default password has been sent to your email.",
                    UnableToVerifyBVN: "Unable to verify BVN with thirdparty.",
                    FailedUpload: "Unable to upload file",
                    UploadFileError: "Upload file",
                    SuccessfulUpload: "Image upload successful",
                    CustomerNotFound: "Customer record not found",
                    WalletNotFound: "Customer wallet  not found",
                    Failed: "Failed to complete action",
                    CustomerOrBvnEmpty: "Customer or BVN not found",
                    FailedLinkAccount: "Invalid Account Linking. You can only link your account number",
                    Successful: "Completed Successfully",
                    UnableToChargeCard: "Something went wrong while charging card.",
                    UnableToVerifyCardTransaction: "Something went wrong confirming transaction.",
                    FailedTransactionInitialization: "Sorry, we are unable to start this transaction.",
                    InvalidGLTransactionType: "Sorry, the transaction type is invalid.",
                    WalletFundingNarration: "Wallet funding",
                    IndeterminateTransaction: "Sorry, we are unable to determine the status of this transaction.",
                    SuccessfulWalletFunding: "You have successfully funded your wallet.",
                    WalletFundingSQLError: "Sorry, something went wrong while processing transaction",
                    CardNotFoundError: "Sorry, we could not find the selected card on your profile",
                    SuccessfulGLCreation: "GL Account created successfully",
                    GLCreationFailed: "GL Account creation failed",
                    GLAlreadyExist: "GL Already Exist",
                    InvalidTransactionReference: "Invalid Transaction Reference",
                    UnableToCompleteThisTransactionPleaseContactCustomerSupport: "Unable To Complete This Transaction. Please Contact Customer Support.",
                    BankAccountLinked: "Sorry, this bank account has been linked to another wealth buddy account.",
                    FailedAccountLink: "You Can Only Link Your Bank Account With The Registered BVN",
                    AccountEnquiryFailed: "Account Enquiry Failed",
                    BankAccountVerificationFailed: "Bank Account Verification Failed",
                    BankAccountAlreadyVerified: "Bank Account Already verified",
                    BillsPaymentCategories: "Bills payment category successfully fetched",
                  
            }
